project:
  type: website

website:
  title: "cwick.co.nz"
  search: false
  open-graph: true 
  page-footer: "Built with [Quarto](http://quarto.org)"
  navbar:
    id: top-nav
    pinned: true
    toggle-position: right
    right:
      - talks/index.qmd
      - workshops/index.qmd
      - teaching/index.qmd

format:
  html:
    theme: [cosmo, styles.scss] 
