project:
  type: website

website:
  title: "Albert Anesu Chimbi"
  site-url: your-site-url-here # Replace with your actual site URL
  search: false
  open-graph: true
  page-footer:
    left: "[Source](https://github.com/Anesu-Chimbi/Shiny_OSM_Features)"
    right: "Built with {{< iconify mdi:heart >}} and {{< iconify simple-icons:quarto >}} [Quarto](http://quarto.org)"
  navbar:
    id: top-nav
    pinned: true
    toggle-position: right
    right:
      - index.qmd
      - about.qmd
      - projects.qmd
      - contact.qmd
    tools:
      - icon: github
        text: GitHub
        href: https://github.com/Anesu-Chimbi
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/albert-anesu-chimbi/

format:
  html:
    theme: [cosmo, styles.scss]
